### ISSUE TITLE
Crashed when I used the Knight file and will never work

### ISSUE THREAD

**Issue by MrNoobieIG** [cmot17/CustomKnight-Creator#11]
#For some reason my Custom Knight Crashed when I used the Knight folder and when I tried opening the application more then 100+ times it wouldn't work ever again. I don't know why this happened
![Screenshot (284)](https://user-images.githubusercontent.com/117902071/201051070-88460326-a5c3-453a-a78d-824b8a114bc5.png)
![Screenshot (285)](https://user-images.githubusercontent.com/117902071/201051133-7fa833fd-a1d9-459f-9b45-ca1f168f9682.png)
![Screenshot (286)](https://user-images.githubusercontent.com/117902071/201051181-8211e5fd-868d-4155-b738-6998a96ba439.png)
![Screenshot (287)](https://user-images.githubusercontent.com/117902071/201051233-daddc36b-aa87-456e-9b69-0c4714712dc7.png)

**Comment by MrNoobieIG** [comment]
This is my first time using it and this happens

**Comment by cmot17** [comment]
Did you resolve the issue?
