### ISSUE TITLE
CustomKnight not opening after selecting root folder 

### ISSUE THREAD

**Issue by FoolixtheFool** [cmot17/CustomKnight-Creator#12]
when trying to open ,presented with this message 
![image](https://user-images.githubusercontent.com/74905061/215860485-904f03f5-8eb4-4f32-b74b-d0ecb73a43fc.png)

I'm using windows 10

**Comment by Nidoskull** [comment]
Can confirm this issue, also on Windows 10.
Seems like the program's looking for a file that doesn't exist, "/0.Atlases/SpriteInfo.json'" in the root folder, but I have no idea where I'd find it x)

**Comment by sigla007** [comment]
go to your c or d drive(which ever has the users folder), then click on users,click the user that has the custom knight creator then delete the saveslot
i dont know if this delete your progress but thats the only way i know of
