### ISSUE TITLE
Program not Loading on Mac

### ISSUE THREAD

**Issue by Stella68958** [cmot17/CustomKnight-Creator#14]
I've been trying to open this up and continue a  project however I would start loading, stop, start again, then stop again. When loading with the exec window open I get this. I have the Sprites folder so I'm not sure what the issue is. If anyone knows how to fix this I'm willing to try anything!

![Screen Shot 2023-10-20 at 10 48 53 PM](https://github.com/cmot17/CustomKnight-Creator/assets/148609953/a2472cbd-9af4-49e4-8453-efd9e36052b7)

**Comment by Stella68958** [comment]
I just looked at a closed case with a similar issue; How does deleting a saved state help? I don't want to lose all my work if possible

**Comment by cmot17** [comment]
@Stella68958 have you tried [this?](https://github.com/cmot17/CustomKnight-Creator/wiki/Common-Problems#my-program-crashed-and-no-longer-openshas-stopped-working)

**Comment by Stella68958** [comment]
> @Stella68958 have you tried [this?](https://github.com/cmot17/CustomKnight-Creator/wiki/Common-Problems#my-program-crashed-and-no-longer-openshas-stopped-working)

When I mentioned deleting a save state, this is what I was referring to lol. Mac doesn't have the user folder easily accessible and I didn't want to lose all my progress. I was hoping there was a way to fix this without deleting it. But I did end up just deleting it.

But future mac users might find this helpful:

to access users you gotta enable seeing the hard drive. To do this go to Finder, then in the **Finder** dropdown window select Preferences and navigate to sidebar.
