### ISSUE TITLE
unhandled exception 

### ISSUE THREAD

**Issue by Drafy07** [cmot17/CustomKnight-Creator#16]
![image](https://github.com/cmot17/CustomKnight-Creator/assets/50578765/fad2eec5-9a32-405b-9ed7-f61ce585b522)

to recreate : deleting a folder you previously loaded and then trying to launch the app

**Comment by cmot17** [comment]
https://github.com/cmot17/CustomKnight-Creator/wiki/Common-Problems#my-program-crashed-and-no-longer-openshas-stopped-working
