### ISSUE TITLE
I get an error and the app won't start-up.

### ISSUE THREAD

**Issue by madphantom69** [cmot17/CustomKnight-Creator#18]
I tried making a skin without any previous knowledge. And now I keep getting this error:

Traceback (most recent call last):
  File "main.py", line 450, in <module>
  File "main.py", line 22, in __init__
  File "main.py", line 295, in recoverSavedState
  File "main.py", line 89, in loadCategories
  File "spritehandler.py", line 36, in loadSpriteInfo
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Games\\Hollow Knight\\Hollow Knight_Data\\Managed\\Mods\\Custom Knight\\Skins\\Hollow/0.Atlases/SpriteInfo.json'

I tried to run a folder with sprites and now I'm locked out of the app.
Even if I re-extract the folders from the apps zip, it just keeps giving me the error and exiting afterwards.

**Comment by Ashio-Suzaku** [comment]
Same here

**Comment by zGlace** [comment]
You can fix this problem by navigating to your user folder, "Customknight Creator" and then deleting "savestate.json".

**Comment by madphantom69** [comment]
> You can fix this problem by navigating to your user folder, "Customknight Creator" and then deleting "savestate.json".

Thank you, this actually fixed it.
