### ISSUE TITLE
Told program to load categories in bad folder, now it's unusable

### ISSUE THREAD

**Issue by luxidoptera** [cmot17/CustomKnight-Creator#2]
Hi, so I have a critical bug to report- I misunderstood the directions for using this program and tried to tell it to load categories in a folder without the necessary files inside it, and have managed to render it completely unusable by doing so. It initially crashed, and now throws the same error on boot every time I run it. It really takes a moron to find a bug this terrible, huh.

![image](https://user-images.githubusercontent.com/15697751/149755495-dd1f4c22-2e3d-4afe-b95b-8b9dc3c77f51.png)

Deleting and replacing the .exe doesn't work, and I can't figure out where it stores this information so I can clear it. Please help.

**Comment by AcroLikesBeans** [comment]
"Navigate to your user folder, then 'Customknight Creator'. Delete 'savestate.json'. This is not a big deal; you will just have to show the program where your root folders are and where to output again. This should fix most or all problems you have with the program breaking or not opening."

**Comment by luxidoptera** [comment]
Thanks, I must've missed that.
