### ISSUE TITLE
when attempting to check for duplicates of any spell file CKC crashes. not just this but the spells i have reanimated by hand dont appear ingame

### ISSUE THREAD

**Issue by SushiSenpai0512** [cmot17/CustomKnight-Creator#6]
also attempting to check for duplicates in the shade folder makes it crash

**Comment by Northflowo** [comment]
I have the same problem, but with the Hollow Shade file. I have tried to reinstall just to make sure it wasn't something on my end, but the issue persists...

**Comment by cmot17** [comment]
@SushiSenpai0512 @Northflowo https://github.com/cmot17/CustomKnight-Creator/releases/tag/v1.0.2 should fix the crash. 

@SushiSenpai0512, if the spell reanimation issue is still occurring, can you open a new issue with some more details?
