### ISSUE TITLE
I keep getting an error. Unhandled exception in script

### ISSUE THREAD

**Issue by Jackferg059** [cmot17/CustomKnight-Creator#7]
After adding the file for the knight the creator crashed, I tried opening it again and it gave me this error;

Traceback (most recent call last):
  File "main.py", line 433, in <module>
  File "main.py", line 21, in __init__
  File "main.py", line 288, in recoverSavedState
  File "main.py", line 87, in loadCategories
  File "spritehandler.py", line 36, in loadSpriteInfo
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\___\\Downloads\\Knight-20220623T023524Z-001/0.Atlases/SpriteInfo.json'

After deleting both files of the knight sheet and the creator I still kept getting both of these errors over and over again. and I'm not sure how I would fix this issue.

**Comment by cmot17** [comment]
Can you try deleting your program's saved state by following these directions?
 https://github.com/cmot17/CustomKnight-Creator/wiki/Common-Problems#my-program-crashed-and-no-longer-openshas-stopped-working

**Comment by cmot17** [comment]
Also, where did you download the HK sprites from? Your folders look like they might be in a different format.

**Comment by cmot17** [comment]
Closing due to no response
