### ISSUE TITLE
Errors when trying to open CustomKnight Creator for the first time

### ISSUE THREAD

**Issue by rinjaespurr6** [cmot17/CustomKnight-Creator#8]
When I'm trying to open CustomKnight Creator for the first time, I'm getting two errors. The first one says "No error messages generated FormatMessageW: The parameter is incorrect.", the second one says "Error loading Python DLL 'C:\Users\Admin\AppData\Local\Temp\_MEI59602\python310.dll'. LoadLibrary: PyInstaller: FormatMessageW failed."
I'm using windows 7. Is there any way to fix this problem?

![error1](https://user-images.githubusercontent.com/110311062/182001720-f62414dc-1cbc-40e7-819d-5d1013f140ae.png)
![error2](https://user-images.githubusercontent.com/110311062/182001722-f520c3ae-43bc-4525-b3c8-812d2309fff4.png)

**Comment by cmot17** [comment]
Windows 7 is probably the issue. You can try running the python source directly and that might work
