### ISSUE TITLE
Selecting the folder

### ISSUE THREAD

**Issue by RyePerhaps** [cmot17/CustomKnight-Creator#9]
I selected the folder, and immediately it shut down the program. Now I cannot open the program at all. I know I likely made a mistake using it, ive never used it before this, but also cannot fix the issue now. 
I have redownloaded the file, deleted the original program, and nothing worked to fix it
![image](https://user-images.githubusercontent.com/114880893/193473412-419a7942-33fc-4d32-b28f-a67dae4e843e.png)
Image of the error given

**Comment by cmot17** [comment]
Try these steps from the wiki:

> Navigate to your user folder, then "Customknight Creator". Delete "savestate.json". This is not a big deal; you will just have to show the program where your root folders are and where to output again. This should fix most or all problems you have with the program breaking or not opening.

**Comment by RyePerhaps** [comment]
> 

Thank you :'D
